USE PHONE_BOOK;

--CREATE USER 'phonebook'@'localhost' IDENTIFIED BY 'phonebook';

CREATE TABLE PHONEBOOK (
    ID       BIGINT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME     VARCHAR(100) NOT NULL
); 

CREATE TABLE ENTRY(
ID     			   BIGINT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT, 
NAME                       VARCHAR(50),
PHONENUMBER                VARCHAR(150) UNIQUE NOT NULL,
PHONEBOOKID		   BIGINT,
FOREIGN KEY (PHONEBOOKID)  REFERENCES  PHONEBOOK(ID)
);
